calico/src/main/scala/calico/DeferredSignallingRef.scala
calico/src/main/scala/calico/syntax.scala
docs/index.md
docs/time.md

Closes https://github.com/armanbilge/calico/issues/1.

Add `DeferredSignallingRef`

---

.github/workflows/ci.yml
build.sbt
calico/src/main/scala/calico/dsl.scala
calico/src/main/scala/calico/syntax.scala
docs/directory.conf
docs/todomvc.md
docs/todomvc/index.html
todo-mvc/index.html
todo-mvc/src/main/scala/todomvc/TodoMvc.scala

Plus various changes as I figure out how to make this stuff work.
This will be a WIP, but it's currently a MVP.

Implement TodoMVC example app

---

calico/src/main/scala/calico/dsl.scala
calico/src/main/scala/calico/syntax.scala
todo-mvc/src/main/scala/todomvc/TodoMvc.scala

Notably overuse of `Element` and `HTMLElement` etc.

Relax constraints

---

calico/src/main/scala/calico/dsl.scala
todo-mvc/src/main/scala/todomvc/TodoMvc.scala

But let's keep iterating on the API.

Relax constraints for keyed children modifier

---

calico/src/main/scala/calico/syntax.scala
docs/time.md
widget/src/main/scala/calico/widget/Widget.scala

This is an incorrect implementation of `Signal`. `Stream#holdOptionResource` is what I wanted.

Deprecate extension `Stream#signal`

---

docs/index.md

Closes https://github.com/armanbilge/calico/issues/38.

Add docs about scheduling, microtasks, macrotasks

---

calico/src/main/scala/calico/dsl.scala

fixes https://github.com/armanbilge/calico/issues/83
Not sure if this is correct, but these changes have been working for me in my very limited use.
- use a placeholder comment node to keep track of insertion position within the parent node
- remove individual children with removeChild instead of replaceChildren

fix children clobber bug

---

build.sbt
todo-mvc/src/main/scala/todomvc/TodoMvc.scala

This is super fun. Especially to open two todo windows and watch them stay synchronized 😃
The catch is that this will probably break the benchmarking code.

Use local storage for persistent todos

---

.github/workflows/ci.yml
build.sbt
sandbox/index.html
sandbox/src/main/scala/calico/Sandbox.scala

It's not meant to be an example, it's useful for trying out WIP changes.

Rename `example` as `sandbox`

---

calico/src/main/scala/calico/html/HtmlTag.scala
project/src/main/scala/calico/html/codegen/CalicoGenerator.scala
project/src/main/scala/calico/html/codegen/DomDefsGenerator.scala

Closes https://github.com/armanbilge/calico/issues/152.

Remove `HtmlTagT`

---

calico/src/main/scala/calico/syntax.scala

Fixes https://github.com/armanbilge/calico/issues/133.
Let me know if this fixes your issue. Sorry for using the cheap hack before 😂

Unhack `getAndUpdates`

---

frp/src/test/scala/calico/frp/SignalSuite.scala

This reverts commit aff264318acdcbe55d893fc66f5980c3cdcc51d0.
Stil broken 😕

Revert "Restore all the `Monad` law tests"

---

.github/workflows/ci.yml
README.md
build.sbt
docs/index.md
router/src/main/scala/calico/router/Router.scala
router/src/main/scala/calico/router/Routes.scala

Closes https://github.com/armanbilge/calico/issues/135.

Prepare site for 0.2.x series and publish from `main`

---

calico/src/main/scala/calico/html/Prop.scala
project/src/main/scala/calico/html/codegen/CalicoGenerator.scala
project/src/main/scala/calico/html/codegen/DomDefsGenerator.scala

Closes https://github.com/armanbilge/calico/issues/167.
I think this is a really interesting idea. I'm a bit worried if it makes `EventProp` a more confusing API, but I am not sure how user-facing it is anyway.

`EventProp` is a `Functor`

---

build.sbt
calico/src/main/scala/calico/IOWebApp.scala
calico/src/main/scala/calico/html/Html.scala
docs/router.md
router/src/main/scala/calico/router/Router.scala
sandbox/src/main/scala/calico/Sandbox.scala
todo-mvc/src/main/scala/todomvc/TodoMvc.scala

The main idea is that now everything works through `Window[IO]`.

Upgrade to fs2-dom v0.2.0-M3

---

build.sbt
frp/src/main/scala/calico/frp/SignallingSortedMapRef.scala
frp/src/test/scala/calico/frp/SignallingSortedMapRefSuite.scala

A handful of optimizations, refactors, and fixes. Closes https://github.com/armanbilge/calico/issues/139.

Refresh `SignallingSortedMapRef`

---

frp/src/main/scala/calico/frp/frp.scala

Forgot these. More optimizations, yay!

Override `getAndDiscreteUpdates` for `Monad[Signal]`

---

calico/src/main/scala/calico/html/HtmlAttr.scala

Fix attribute modifiers

---

build.sbt
docs/demos/http4s.md

Closes https://github.com/armanbilge/calico/issues/218.

Add demo for `FetchClient`

---

router/src/main/scala/calico/router/Router.scala

`Router#teleport` should use `replaceState`

---

frp/src/main/scala/calico/frp/frp.scala

So we don't have to replicate fixes like https://github.com/typelevel/fs2/pull/3206.
Also instead of `ap` we override `product` and `map2` instead, since it turns out `FlatMap` was overriding those with `flatMap` based implementations. I think they are the most commonly used ones and there is a performance win since `flatMap` involves tearing down and restarting the inner signal.

Delegate to upstream `Applicative[Signal]`

---

docs/concepts.md
docs/demos/counter.md
docs/demos/hello-world.md
docs/demos/http4s.md
docs/demos/time.md
docs/iowebapp.md
docs/router.md

This is now convenient syntax on `IO`.

Use `toResource` everywhere in docs

---

.scala-steward.conf

So that we can get sbt and scalafmt updates.

Fix file extensions in steward config
